
import './globals.css';
import Head from 'next/head';

export const metadata = {
  title: 'Portfolio',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <>
      <body className='max-w-7xl mx-auto'>{children}</body>
      
    </>
  );
}